package com.asensiodev.carbura.core.stringresources

enum class CarburaString {
    GarageTitle,
    GarageSubtitle,
    VehicleFormTitle,
    VehicleNameLabel,
    CurrentOdometerLabel,
    SaveVehicleButton,
    EmptyGarageTitle,
    EmptyGarageDescription,
    ViewHistoryButton,
    VehicleCreatedMessage,
    ValidationBlankVehicleName,
    ValidationNegativeVehicleOdometer,
    ValidationGeneric,
    MaintenanceBackButton,
    MaintenanceTitle,
    MaintenanceSubtitle,
    MaintenanceFormTitle,
    MaintenanceTypeLabel,
    MaintenanceDateLabel,
    MaintenanceOdometerLabel,
    MaintenanceCostLabel,
    MaintenanceWorkshopLabel,
    MaintenanceNotesLabel,
    SaveMaintenanceButton,
    MaintenanceHistoryTitle,
    EmptyMaintenanceHistoryTitle,
    EmptyMaintenanceHistoryDescription,
    MaintenanceCreatedMessage,
    ValidationBlankMaintenanceType,
    ValidationInvalidMaintenanceDate,
    ValidationNegativeMaintenanceOdometer,
    ValidationNegativeMaintenanceCost,
}
